apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-pins-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-pins-api
  template:
    metadata:
      labels:
        app: simple-pins-api
    spec:
      containers:
      - name: api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_NAME
          value: "simple_pins_api"
        - name: JWT_ALGORITHM
          value: "HS256"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: simple-pins-api
  ports:
  - port: 80
    targetPort: 8000
